#
# Copyright (c) Microsoft Corporation
# Licensed under the MIT License.
# Self Hosted Runner Activated

#iteration 2 workflow!

# Running workflow_dispatch

name: 1 - landingzone-launchpad

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Secret to Deploy Launchpad? Use lower case (no, yes)"
        default: "no"

env:
  TF_CLI_ARGS: "-no-color"
  TF_CLI_ARGS_destroy: "-auto-approve -refresh=false"
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ALZ_NAME: "ALZ"
  ROVER_RUNNER: true

jobs:
  alz-foundations:
    name: foundations
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        random_length: ["5"]

    container:
      image: aztfmod/rover:0.14.8-2103.1601
      options: --user 0

    steps:
      - uses: actions/checkout@v2

      - name: Login azure
#        if: ${{ github.event.inputs.confirm == 'yes' }}
        run: |
          az login --service-principal -u '${{ env.ARM_CLIENT_ID }}' -p '${{ env.ARM_CLIENT_SECRET }}' --tenant '${{ env.ARM_TENANT_ID }}'
          az account set -s  ${{ env.ARM_SUBSCRIPTION_ID }}
          echo "set subscription to ${{ env.ARM_SUBSCRIPTION_ID }} "
          echo "local user: $(whoami)"
      - name: launchpad
        if: ${{ github.event.inputs.confirm == 'yes' }}
        run: |
          /tf/rover/rover.sh -lz ${GITHUB_WORKSPACE}/tf/caf/caf_launchpad -a apply \
            -var-folder ${GITHUB_WORKSPACE}/configs/launchpad \
            -level level0 \
            -launchpad \
            -parallelism=30 \
            --environment ${{ env.ALZ_NAME }} \
            -var prefix=""
      - name: foundations
        if: ${{ github.event.inputs.confirm == 'yes' }}
        run: |
          /tf/rover/rover.sh -lz ${GITHUB_WORKSPACE}/tf/caf/caf_foundations -a apply \
            -level level1 \
            -parallelism=30 \
            --environment ${{ env.ALZ_NAME }}